# Generated by Django 2.2.7 on 2019-11-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('school_id', models.CharField(max_length=200)),
                ('attendence', models.CharField(max_length=800)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classes')),
            ],
        ),
    ]
