# Generated by Django 2.2.7 on 2019-11-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courseId',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='login.Classes'),
        ),
    ]
