# Generated by Django 2.2.7 on 2019-11-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191123_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classes'),
        ),
    ]
