# Generated by Django 2.2.7 on 2019-11-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191123_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='courseId',
            new_name='courseName',
        ),
    ]
