# Generated by Django 2.2.7 on 2019-11-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191124_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='courseName',
            new_name='courseId',
        ),
    ]
