# Generated by Django 2.2.7 on 2019-11-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_classes_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='first_name',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
        migrations.AddField(
            model_name='students',
            name='studentPicture',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
