# Generated by Django 2.2.7 on 2019-11-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191124_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentPicture',
            field=models.FileField(default=1, upload_to='student_pics/'),
        ),
    ]
