# Generated by Django 2.2.7 on 2019-11-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191124_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentPicture',
            field=models.FileField(default=1, upload_to='../students/student_pics/'),
        ),
    ]
