# Generated by Django 2.2.7 on 2019-11-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191124_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class+', to='login.Classes'),
        ),
    ]
