# Generated by Django 2.2.7 on 2019-11-24 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191124_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers+', to=settings.AUTH_USER_MODEL),
        ),
    ]
