# Generated by Django 2.2.7 on 2019-11-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20191127_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Classes'),
        ),
    ]
