# Generated by Django 2.2.7 on 2019-11-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20191127_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='students',
            name='studentPicture',
            field=models.ImageField(default=1, upload_to='students/'),
        ),
    ]
