# Generated by Django 2.2.7 on 2019-11-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20191127_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='courseId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='courseId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='school_id',
            field=models.CharField(max_length=300),
        ),
    ]
