# Generated by Django 2.2.7 on 2019-12-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20191130_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='students',
            name='courseId',
        ),
        migrations.AlterField(
            model_name='students',
            name='studentPicture',
            field=models.ImageField(default=1, null=True, upload_to='students/'),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='login.Classes')),
                ('attendanceStudents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='login.Students')),
            ],
        ),
    ]
