# Generated by Django 2.2.7 on 2019-12-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20191202_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendanceStudents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='login.Students'),
        ),
    ]
