# Generated by Django 2.2.7 on 2019-12-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20191202_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendanceStudents',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='login.Students'),
        ),
    ]
