# Generated by Django 2.2.7 on 2019-12-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20191202_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendanceStudents',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_students', to='login.Students'),
        ),
    ]
