# Generated by Django 2.2.7 on 2019-12-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20191202_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendanceClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='login.Classes'),
        ),
    ]
