# Generated by Django 2.2.7 on 2019-12-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20191202_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='attendanceStudents',
        ),
        migrations.AddField(
            model_name='students',
            name='classEnrolled',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='classes_enrolled', to='login.Classes'),
        ),
    ]
