# Generated by Django 2.2.7 on 2019-12-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20191202_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='classEnrolled',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_enrolled', to='login.Classes'),
        ),
    ]
