# Generated by Django 2.2.7 on 2019-12-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20191202_0505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
    ]
