# Generated by Django 2.2.7 on 2019-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_delete_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='attendence',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
